# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_hello_world <- function(m, n, d) {
    .Call(`_BMM_rcpp_hello_world`, m, n, d)
}

